### PR TITLE
Preserve regular blockquotes

### PR DESCRIPTION
**Pull request by ehsandarroudi**
> Some email clients (e.g. Apple Mail) add blockquotes when you indent text or when you copy & paste a part from the original message.
> Instead of removing the blockquote element wrapping the original message, talon just removes the first blockquote it finds.
> 
> I'm using an xpath expression to only select the last blockquote in the message. It can also handle nested blockquotes.

Copied from https://github.com/mailgun/talon/pull/50.

### CODE REVIEW

**Comment by tgwizard** [comment]
Thanks, LGTM. Although what if you actually reply inline to the HTML message, won't there be multiple `<blockquote>` tags after `On 11-Apr-2011, at 6:54 PM, Bob &lt;bob@example.com&gt; wrote:` that should be stripped?

**Comment by ehsandarroudi** [comment]
IMO, they shouldn't be stripped in that case, cause you would want to know what the inline reply refers to.
Anyway, the difference between the two implementations in that case is, that the original implementation removes the first `blockquote` and my implementation the last.

**Comment by tgwizard** [comment]
For text emails everything with `>` is stripped (no?), so those emails behave differently then.

But if that's the real change (first vs. last blockquote), I'm fine with this.

**Comment by ehsandarroudi** [comment]
I did a quick test: for text emails nothing is stripped when you have inline replies, not even the splitter line.
And yes, the change here is only first vs. last blockquote.

**Comment by tgwizard** [comment]
Thanks for checking @Easy-D!

**Comment by tgwizard** [comment]
This is now released in v1.2.0 of claw.

**Pull request merged**
