### PR TITLE
Support for Scandinavian languages

### PR DESCRIPTION
**Pull request by simonflore**
Some support was missing for a few use cases in Norwegian, Danish, Swedish.

### CODE REVIEW

**Comment by simonflore** [comment]
@tgwizard Any idea why CircleCI failed? My tests are running fine.

**Comment by tgwizard** [comment]
Sorry, my bad. I fixed it in #7, so if you rebase from master the tests should pass.

**Comment by tgwizard** [comment]
Great, thanks @simonflore. Perhaps you should submit this PR to https://github.com/mailgun/talon as well, the mailgun people seem to be more active now.

**Comment by tgwizard** [comment]
This has been released as v1.3.0 of claw, and is available on PyPI.

**Pull request merged**
